<?php
interface nomSuccursale
{
    const Joliette = 1;
    const Anjou = 2;
    const Boucherville = 3;
    const SaintHyacinthe = 4;
    const Drummondville = 5;
    const Victoriaville = 6;
    const TroisRivieres = 7;
    const ThetfordMines = 8;
    const SaintGeorges = 9;
    const RiviereDuLoup = 10;
    const Quebec = 11;
    const Shawinigan = 12;
    const Chicoutimi = 13;
    const Clermont = 14;
    const Forestville = 15;
    const Matane = 16;
    const Rimouski = 17;
    const RiviereAuRenard = 18;
    const SeptIles  = 19;
    const SainteMarieDeBeauce = 20;
}

class Contact{
    private $nom = '';
    private $email = '';
    private $titre = '';
    
    private $contacts = array();

    public function addItem($obj, $key = null) {
        if ($key == null) {
            $this->items[] = $obj;
        }
        else {
            if (isset($this->items[$key])) {
                throw new KeyHasUseException("Key $key already in use.");
            }
            else {
                $this->items[$key] = $obj;
            }
        }
    }

    public function deleteItem($key) {
        if (isset($this->items[$key])){
            unset($this->items[$key]);
        }
        else {
            throw new KeyInvalidException("Invalid key $key.");
        }
    }

    public function getItem($key) {
        if (isset($this->items[$key])) {
            return $this->items[$key];
        }
        else {
            throw new KeyInvalidException("Invalid key $key.");
        }
    }    
}

class Succursales{
    public $id = 0;
    public $nom = "";
    public $nomLong = "";
    public $telephones = "";
    public $adresse = "";
    public $ville = "";
    public $codePostal = "";
    public $province = "";
    public $isSuccursale = "0";
    public $isPointService = "1";
    public $imageBatisse;
    public $imageBatisseALT;
    public $contacts;
    public $heureOuvertureLundi = "";
    public $heureOuvertureMardi = "";
    public $heureOuvertureMercredi = "";
    public $heureOuvertureJeudi = "";
    public $heureOuvertureVendredi = "";
    public $heureOuvertureSamedi = "";
    public $heureOuvertureDimanche = "";
    public $servicesOfferts;
    public $serviceRoutierTitre = "";
    public $serviceRoutierTelephone = "";
    public $remorquageTitre = "";
    public $remorquageInfo = "";
    public $remorquageTelephones = "";
    private $parametreBonTravailNomSuccursale = "";
    private $parametreDemandePiecesNomSuccursale = "";
    public $GoogleMapSRC = "";
    
    public function getSuccursaleBonTravail()
    {
        return urlencode($this->parametreBonTravailNomSuccursale);
    }
    
    public function getSuccursaleDemandePieces()
    {
        return urlencode($this->parametreDemandePiecesNomSuccursale);
    }
    
    public function load($succursale){
        
        switch($succursale)
        {
            case nomSuccursale::Drummondville:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Centre du Camion Beaudoin";
                $this->adresse = "5360, rue St-Roch";
                $this->ville = "Drummondville";
                $this->province = "Québec";
                $this->codePostal = "J2B 6V4";
                $this->telephones[] = "Téléphone : 819 478-8186";
                $this->telephones[] = "Sans frais : 800 463-8186";
                $this->telephones[] = "Télécopieur : 819 472-1484";
                $this->heureOuvertureLundi = "7:00 - 00:30";
                $this->heureOuvertureMardi = "7:00 - 00:30";
                $this->heureOuvertureMercredi = "7:00 - 00:30";
                $this->heureOuvertureJeudi = "7:00 - 00:30";
                $this->heureOuvertureVendredi = "7:00 - 00:30";
                $this->heureOuvertureSamedi = "7:00 - 12:00";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Steve Hallé", "Président Directeur Général", "shalle@camionbeaudoin.com"));
                $this->contacts->addItem(array("Pierre Lamothe", "Directeur des ventes", "plamothe@camionbeaudoin.com"));
                $this->contacts->addItem(array("Michel Marquis", "Directeur des pièces", "mmarquis@camionbeaudoin.com"));
                $this->contacts->addItem(array("Jean-François Taillon", "Directeur du services", "jftaillon@camionbeaudoin.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-centre-du-camion-beaudoin.jpg";
                $this->imageBatisseALT= "Centre du Camion Beaudoin";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Air climatisé";
                $this->servicesOfferts[] = "Produits de réfrigération Carrier";
                $this->servicesOfferts[] = "Alignement";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Idealease";
                $this->servicesOfferts[] = "Service routier";
                $this->servicesOfferts[] = "Remorquage";
                $this->servicesOfferts[] = "Distributeur Ottawa Kalmar";
                $this->servicesOfferts[] = "Stationnement pour remorque";
                $this->servicesOfferts[] = "Réparation de remorque";
                $this->serviceRoutierTitre = "Service Routier";
                $this->serviceRoutierTelephone[] = "Dimanche 00:00 au samedi 8:00";
                $this->serviceRoutierTelephone[] = "Téléphone : 819 478-8186";
                $this->remorquageTitre = "Remorquage Québec Centre";
                $this->remorquageInfo[] = "5360, rue St-Roch";
                $this->remorquageInfo[] = "Drummondville (Québec)";
                $this->remorquageInfo[] = "J2B 6V4";
                $this->remorquageTelephones[] = "Pagette : 819 472-8784";
                $this->remorquageTelephones[] = "Cellulaire : 819 472-9498";
                $this->remorquageTelephones[] = "Cellulaire : 819 314-2152";
                $this->parametreBonTravailNomSuccursale = "Centre%20du%20Camion%20Beaudoin";
                $this->parametreDemandePiecesNomSuccursale = "Centre%20du%20Camion%20Beaudoin";
                break;
            case nomSuccursale::Joliette:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Camions Inter-Lanaudière";
                $this->adresse = "791, Samuel Racine";
                $this->ville = "Joliette";
                $this->province = "Québec";
                $this->codePostal = "J6E 0E8";
                $this->telephones[] = "Téléphone : 450 760-9996";
                $this->telephones[] = "Pièces : 450 760-3135";
                $this->telephones[] = "Services : 450 760-3510";
                $this->telephones[] = "Télécopieur : 450 760-3585";
                $this->heureOuvertureLundi = "7:00 - 0:00";
                $this->heureOuvertureMardi = "7:00 - 0:00";
                $this->heureOuvertureMercredi = "7:00 - 0:00";
                $this->heureOuvertureJeudi = "7:00 - 0:00";
                $this->heureOuvertureVendredi = "7:00 - 0:00";
                $this->heureOuvertureSamedi = "Fermé";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Sébastien Gagné", "Président","sebastieng@camionsinterlanaudiere.com"));
                $this->contacts->addItem(array("Patrick Vig", "Directeur service","patrickv@camionsinterlanaudiere.com"));
                $this->contacts->addItem(array("Benoit Blier", "Contremaître","benoitb@camionsinterlanaudiere.com"));
                $this->contacts->addItem(array("Richard Lépine", "Directeur des pièces","richardl@camionsinterlanaudiere.com"));
                $this->contacts->addItem(array("Pierre Harnois", "Représentant des pièces et service","pierreh@camionsinterlanaudiere.com"));
                $this->contacts->addItem(array("Nadine Beauparlant", "Représentant des pièces et service","nadineb@camionsinterlanaudiere.com"));
                $this->contacts->addItem(array("Guillaume Coutu", "Représentant des pièces et service","guillaumec@camionsinterlanaudiere.com"));
                $this->contacts->addItem(array("Alex Calvé", "Représentant vente camion neuf, usagé et location","alexc@camionsinterlanaudiere.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-camions-inter-lanaudiere.jpg";
                $this->imageBatisseALT= "Camions Inter-Lanaudière";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Service routier";
                $this->servicesOfferts[] = "Remorquage";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Air climatisé";
                $this->servicesOfferts[] = "Stationnement pour remorque";
                $this->servicesOfferts[] = "Réparation de remorque";
                $this->serviceRoutierTitre = "Service Routier 24/7";
                $this->serviceRoutierTelephone[] = "Jour : 450 760-9996";
                $this->serviceRoutierTelephone[] = "Nuit : 1-844-427-6297";
                $this->remorquageTitre = "Remorquage";
                $this->remorquageInfo[] = "<b>Remorquage Rondeau</b>";
                $this->remorquageInfo[] = "450 887-2970";
                $this->parametreBonTravailNomSuccursale = "Camions%20Inter-Lanaudi%C3%A8re";
                $this->parametreDemandePiecesNomSuccursale = "Camions%20Inter-Lanaudi%C3%A8re%";
                $this->GoogleMapSRC = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d22163.018849870517!2d-73.40596211499049!3d46.02361877120809!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc8bd890a98260f%3A0xbf44a24df56dd942!2s791+Rue+Samuel-Racine%2C+Joliette%2C+QC+J6E+0E8%2C+Canada!5e0!3m2!1sfr!2sfr!4v1408893246410";
                break;
            case nomSuccursale::Anjou:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Camions Inter-Anjou";
                $this->adresse = "8300, rue Edison";
                $this->ville = "Anjou";
                $this->province = "Québec";
                $this->codePostal = "H1J 1S8";
                $this->telephones[] = "Téléphone : 514 353-9720";
                $this->telephones[] = "Télécopieur : 514 353-3222";                
                $this->heureOuvertureLundi = "7:00 - 00:30";
                $this->heureOuvertureMardi = "7:00 - 00:30";
                $this->heureOuvertureMercredi = "7:00 - 00:30";
                $this->heureOuvertureJeudi = "7:00 - 00:30";
                $this->heureOuvertureVendredi = "7:00 - 00:30";
                $this->heureOuvertureSamedi = "Fermé";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Nathalie Hallé", "Présidente","nathalie.halle@camionsinteranjou.com"));
                $this->contacts->addItem(array("Malek Toursal", "Directeur des ventes","malek.toursal@camionsinteranjou.com"));
                $this->contacts->addItem(array("Sylvain Goulet", "Directeur des pièces","sylvain.goulet@camionsinteranjou.com"));
                $this->contacts->addItem(array("Frédéric Benoit", "Directeur du service","frederic.benoit@camionsinteranjou.com"));
                $this->contacts->addItem(array("Sylvain Lalumière", "Directeur Technique","sylvain.lalumiere@reseaudynamique.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-camions-inter-anjou.jpg";
                $this->imageBatisseALT= "Camions Inter-Anjou";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Alignement";
                $this->servicesOfferts[] = "Atelier de carosserie";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Idealease";
                $this->servicesOfferts[] = "Service routier 24/7";
                $this->serviceRoutierTitre = "Service routier 24/7";
                $this->serviceRoutierTelephone[] = "Téléphone : 514 772-1456";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "Camions%20Inter-Anjou";
                $this->parametreDemandePiecesNomSuccursale = "Camions%20Inter-Anjou";
                break;case nomSuccursale::Boucherville:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Inter-Boucherville";
                $this->adresse = "50, chemin du Tremblay";
                $this->ville = "Boucherville";
                $this->province = "Québec";
                $this->codePostal = "J4B 6Z5";
                $this->telephones[] = "Téléphone : 450 655-5050";
                $this->telephones[] = "Montréal : 514 523-5860";
                $this->telephones[] = "Télécopieur : 450 655-5649";
                $this->heureOuvertureLundi = " 	7:00 - 12:45 a.m.";
                $this->heureOuvertureMardi = " 	7:00 - 12:45 a.m.";
                $this->heureOuvertureMercredi = " 	7:00 - 12:45 a.m.";
                $this->heureOuvertureJeudi = " 	7:00 - 12:45 a.m.";
                $this->heureOuvertureVendredi = "7:00 - 19:00";
                $this->heureOuvertureSamedi = "7:00 - 17:00";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Nathalie Hallé", "Présidente","nathalie.halle@camionsinteranjou.com"));
                $this->contacts->addItem(array("Michel Cayer", "Directeur des pièces","michel.cayer@inter-boucherville.com"));
                $this->contacts->addItem(array("Pascal Adam Richard", "Directeur du service","pascaladam.richard@inter-boucherville.com"));
                $this->contacts->addItem(array("Sylvain Lalumière", "Directeur technique","sylvain.lalumiere@camionsinteranjou.com"));
                $this->contacts->addItem(array("Alain Bourgault", "Représentant pièces et service","514-918-5150","alain.bourgault@inter-boucherville.com"));
                $this->contacts->addItem(array("Michel Bélisle", "Représentant pièces et service","514-404-6622" ,"michel.belisle@inter-boucherville.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-inter-boucherville.jpg";
                $this->imageBatisseALT= "Inter-Boucherville";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Alignement";
                $this->servicesOfferts[] = "Atelier de carosserie";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Service routier";
                $this->servicesOfferts[] = "Remorquage";
                $this->serviceRoutierTitre = "Nous offrons Service</br>Routier 24/7";
                $this->serviceRoutierTelephone[] = "Téléphone : 514 772-1456";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "Inter-Boucherville";
                $this->parametreDemandePiecesNomSuccursale = "Inter-Boucherville";
                break;
            case nomSuccursale::SaintHyacinthe:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Les Camions Beaudoin";
                $this->adresse = "3255, rue Picard";
                $this->ville = "St-Hyacinthe";
                $this->province = "Québec";
                $this->codePostal = "J2S 1H3";
                $this->telephones[] = "Téléphone : 450 774-7213";
                $this->telephones[] = "Sans frais : 800 774-7213";
                $this->telephones[] = "Télécopieur : 450 774-3307";
                $this->heureOuvertureLundi = "7:30 - 00:30 a.m.";
                $this->heureOuvertureMardi = "7:30 - 00:30 a.m.";
                $this->heureOuvertureMercredi = "7:30 - 00:30 a.m.";
                $this->heureOuvertureJeudi = " 	7:30 - 00:30 a.m.";
                $this->heureOuvertureVendredi = "7:30 - 00:30 a.m.";
                $this->heureOuvertureSamedi = "8:00 à MIDI";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Roger Lachapelle", "Directeur général","rlachapelle@camionbeaudoin.com"));
                $this->contacts->addItem(array("Pierre Lamothe", "Directeur des ventes","plamothe@camionbeaudoin.com"));
                $this->contacts->addItem(array("Paul Royer", "Directeur des pièces","proyer@camionbeaudoin.com"));
                $this->contacts->addItem(array("Mario Julien", "Directeur du service","mjulien@camionbeaudoin.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-les-camions-beaudoin.jpg";
                $this->imageBatisseALT= "Les Camions Beaudoin";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Air climatisé";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Idealease";
                $this->servicesOfferts[] = "Ramassage et livraison";
                $this->servicesOfferts[] = "Remorquage";
                $this->servicesOfferts[] = "Stationnement pour remorque";
                $this->servicesOfferts[] = "Réparation de remorque";
                $this->serviceRoutierTitre = "Remorquage Québec Centre";
                $this->serviceRoutierTelephone[] = "Téléphone #1 : 819 472-9498";
                $this->serviceRoutierTelephone[] = "Téléphone #2 : 819 478-8186";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "Les%20Camions%20Beaudoin";
                $this->parametreDemandePiecesNomSuccursale = "Les%20Camions%20Beaudoin";
                break;
            case nomSuccursale::Victoriaville:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Charest International";
                $this->adresse = "275, boulevard Pierre Roux Est";
                $this->ville = "Victoriaville (Québec)";
                $this->province = "Québec";
                $this->codePostal = "G6T 1S9";
                $this->telephones[] = "Téléphone : 819 758-8271";
                $this->telephones[] = "Sans frais : 800 567-2519";
                $this->telephones[] = "Télécopieur : 819 758-9900";
                $this->heureOuvertureLundi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureMardi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureMercredi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureJeudi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureVendredi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureSamedi = "8:00 - midi Pièces seulement";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Claude Larochelle", "Directeur général","bill@charestinter.qc.ca"));
                $this->contacts->addItem(array("Pierre Lamothe", "Directeur des ventes","plamothe@camionbeaudoin.com"));
                $this->contacts->addItem(array("Stéphane Lambert", "Directeur des pièces","stephanelambert@charestinter.qc.ca"));
                $this->contacts->addItem(array("Pierre Goulet", "Directeur du service","pierregoulet@charestinter.qc.ca"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-charest-international.jpg";
                $this->imageBatisseALT= "Charest International";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Alignement";
                $this->servicesOfferts[] = "Atelier de carrosserie";
                $this->servicesOfferts[] = "Refrigération";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Idealease";
                $this->servicesOfferts[] = "Air climatisé";
                $this->servicesOfferts[] = "Réparation de remorque";
                $this->servicesOfferts[] = "Service routier";
                $this->serviceRoutierTitre = "Service de remorquage 24/7";
                $this->serviceRoutierTelephone[] = "Remorquage en tout temps au Canada.";
                $this->serviceRoutierTelephone[] = "Téléphone : 819 758-8271";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "";
                $this->parametreDemandePiecesNomSuccursale = "Charest%20International";
                break;
            case nomSuccursale::TroisRivieres:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Garage Charest et Frères";
                $this->adresse = "2250, rue Royale";
                $this->ville = "Trois-Rivières";
                $this->province = "Québec";
                $this->codePostal = "G9A 4L5";
                $this->telephones[] = "Téléphone : 819 376-3754";
                $this->telephones[] = "Sans frais : 800 465-4252";
                $this->telephones[] = "Télécopieur : 819 376-1256";
                $this->heureOuvertureLundi = "7:00 - 00:00";
                $this->heureOuvertureMardi = "7:00 - 00:00";
                $this->heureOuvertureMercredi = "7:00 - 00:00";
                $this->heureOuvertureJeudi = "7:00 - 00:00";
                $this->heureOuvertureVendredi = "7:00 - 00:00";
                $this->heureOuvertureSamedi = "7:00 - 16:00";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Serge Thibodeau", "Président","serge.thibodeau@garagecharest.qc.ca"));
                $this->contacts->addItem(array("Pierre Poudrette", "Directeur général","pierrepoudrette@garagecharest.qc.ca"));
                $this->contacts->addItem(array("Pierre Lamothe", "Directeur des ventes","plamothe@camionbeaudoin.com"));
                $this->contacts->addItem(array("Jean-Pierre Duguay", "Directeur des pièces","jeanpierre.duguay@garagecharest.qc.ca"));
                $this->contacts->addItem(array("André Boisvert", "Directeur du service","andreboisvert@garagecharest.qc.ca"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-charest-freres.jpg";
                $this->imageBatisseALT= "Charest et freres";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Alignement";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Remorquage";
                $this->serviceRoutierTitre = "Service routier 24/7";
                $this->serviceRoutierTelephone[] = "Téléphone : 819 376-3754";
                $this->remorquageTitre = "Remorquage Québec Centre";
                $this->remorquageInfo[] = "Téléphone : 819 472-9498";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "";
                $this->parametreDemandePiecesNomSuccursale = "Garage%20Charest%20et%20Fr%C3%A8res";
                break;
            case nomSuccursale::ThetfordMines:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Le Centre du Camion (Amiante)";
                $this->adresse = "4680, boul. Frontenac Est";
                $this->ville = "Thetford Mines";
                $this->province = "Québec";
                $this->codePostal = "G6H 4G5";
                $this->telephones[] = "Téléphone : 418 338-8588";
                $this->telephones[] = "Sans frais : 800 260-8588";
                $this->telephones[] = "Télécopieur : 418 338-2360";
                $this->heureOuvertureLundi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureMardi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureMercredi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureJeudi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureVendredi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureSamedi = "8:00 - Midi";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Jean-François Poulin", "Directeur des ventes","jfpoulin@centrecamionamiante.com"));
                $this->contacts->addItem(array("Éric Roy", "Directeur des pièces","eroy@centrecamionbeauce.com"));
                $this->contacts->addItem(array("François Jacques", "Directeur du service","fjacques@centrecamionamiante.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-le-centre-du-camion-amiante.jpg";
                $this->imageBatisseALT= "Le Centre du Camion (Amiante)";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Atelier de carosserie";
                $this->servicesOfferts[] = "Réfrigération";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Idealease";
                $this->servicesOfferts[] = "Service routier 24/7";
                $this->servicesOfferts[] = "Remorquage";
                $this->serviceRoutierTitre = "Service routier 24/7";
                $this->serviceRoutierTelephone[] = "Remorquage et dépannage d'urgence au Canada et aux États-Unis.";
                $this->serviceRoutierTelephone[] = "Téléphone : 418 228-8005";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "Le%20Centre%20du%20Camion%20(Amiante)";
                $this->parametreDemandePiecesNomSuccursale = "Le%20Centre%20du%20Camion%20(Amiante)";
                break;
            case nomSuccursale::SaintGeorges:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Le Centre du Camion (Beauce)";
                $this->adresse = "8900, 25e Avenue";
                $this->ville = "Saint-Georges";
                $this->province = "Québec";
                $this->codePostal = "G6A 1K5";
                $this->telephones[] = "Téléphone : 418 228-8005";
                $this->telephones[] = "Sans frais : 1 866 428-8005";
                $this->telephones[] = "Télécopieur: 418 228-3559";
                $this->heureOuvertureLundi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureMardi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureMercredi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureJeudi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureVendredi = "7:30 - 1:00 a.m.";
                $this->heureOuvertureSamedi = "8:00 - Midi";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Donald Pellerin", "Directeur des ventes","dpellerin@centrecamionbeauce.com"));
                $this->contacts->addItem(array("Éric Roy", "Directeur des pièces","eroy@centrecamionbeauce.com"));
                $this->contacts->addItem(array("François Jacques", "Directeur du service","fjacques@centrecamionbeauce.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-le-centre-du-camion-beauce.jpg";
                $this->imageBatisseALT= "Le Centre du Camion (Beauce)";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Alignement";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Idealease";
                $this->servicesOfferts[] = "Remorquage 24/7";
                $this->servicesOfferts[] = "Mandataire SAAQ";
                $this->serviceRoutierTitre = "Remorquage et dépannage d'urgence au Canada et aux États-Unis.";
                $this->serviceRoutierTelephone[] = "Téléphone : 418 228-8005";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "Le%20Centre%20du%20Camion%20(Beauce)";
                $this->parametreDemandePiecesNomSuccursale = "Le%20Centre%20du%20Camion%20(Beauce)";
                break;
            case nomSuccursale::RiviereDuLoup:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Le Centre Routier 1994";
                $this->adresse = "375, Temiscouata";
                $this->ville = "Rivière-du-Loup";
                $this->province = "Québec";
                $this->codePostal = "G5R 3Z5";
                $this->telephones[] = "Téléphone : 418 862-7231";
                $this->telephones[] = "Télécopieur : 418 862-1938";
                $this->heureOuvertureLundi = "7:30 - 00:30";
                $this->heureOuvertureMardi = "7:30 - 00:30";
                $this->heureOuvertureMercredi = "7:30 - 00:30";
                $this->heureOuvertureJeudi = "7:30 - 00:30";
                $this->heureOuvertureVendredi = "7:30 - 00:30";
                $this->heureOuvertureSamedi = "7:30 - 16:30";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Serge Boucher", "Directeur général et Directeur des ventes","sboucher@centreroutier.com"));
                $this->contacts->addItem(array("Jean Fraser", "Directeur des pièces","jfraser@centreroutier.com"));
                $this->contacts->addItem(array("Michel Pelletier", "Directeur du service","mpelletier@centreroutier.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-le-centre-routier-1994.jpg";
                $this->imageBatisseALT= "Le Centre Routier 1994";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Air climatisé";
                $this->servicesOfferts[] = "Produits de réfrigération Carrier";
                $this->servicesOfferts[] = "Produits de réfrigération ThermalKing";
                $this->servicesOfferts[] = "Transmission Allison";
                $this->servicesOfferts[] = "Produits Caterpillar";
                $this->servicesOfferts[] = "Alignement";
                $this->servicesOfferts[] = "Nettoyage de réservoir à carburant";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Idealease";
                $this->servicesOfferts[] = "OnCommand Prev Maint";
                $this->servicesOfferts[] = "Service de partenaire";
                $this->servicesOfferts[] = "VIS Check";
                $this->servicesOfferts[] = "Detroit";
                $this->servicesOfferts[] = "Service routier";
                $this->servicesOfferts[] = "Remorquage";
                $this->servicesOfferts[] = "Stationnement pour remorque";
                $this->servicesOfferts[] = "Réparation de remorque";
                $this->serviceRoutierTitre = "Service routier 24/7";
                $this->serviceRoutierTelephone[] = "Location, remorquage et dépannage d'urgence disponibles en tout temps.";
                $this->serviceRoutierTelephone[] = "Téléphone : 418 862-7231";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "Le%20Centre%20Routier%201994";
                $this->parametreDemandePiecesNomSuccursale = "Le%20Centre%20Routier%201994";
                break;
            case nomSuccursale::Quebec:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Camions International Élite";
                $this->adresse = "265, Étienne-Dubreuil";
                $this->ville = "Québec";
                $this->province = "Québec";
                $this->codePostal = "G1M 4A6";
                $this->telephones[] = "Téléphone : 418 687-9510";
                $this->telephones[] = "Sans frais : 877 687-9510";
                $this->telephones[] = "Télécopieur : 418 687-9518";
                $this->heureOuvertureLundi = "7h30 à minuit";
                $this->heureOuvertureMardi = "7h30 à minuit";
                $this->heureOuvertureMercredi = "7h30 à minuit";
                $this->heureOuvertureJeudi = "7h30 à minuit";
                $this->heureOuvertureVendredi = "7h30 à minuit";
                $this->heureOuvertureSamedi = "Fermé";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Steve Hallé", "Président Directeur Général","shalle@camionbeaudoin.com"));
                $this->contacts->addItem(array("Patrick Gourgues", "Directeur des ventes","pgourgues@inter-quebec.com"));
                $this->contacts->addItem(array("Pierre Desrosiers", "Directeur des pièces","pdesrosiers@inter-quebec.com"));
                $this->contacts->addItem(array("François Després", "Directeur du service","fdespres@inter-quebec.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-camions-international-elite.jpg";
                $this->imageBatisseALT= "Camions International Élite";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Heures de service prolongées";
                $this->servicesOfferts[] = "Air climatisé";
                $this->servicesOfferts[] = "Alignement";
                $this->servicesOfferts[] = "Transmission Allison";
                $this->servicesOfferts[] = "Atelier de carosserie";
                $this->servicesOfferts[] = "Produits Caterpillar";
                $this->servicesOfferts[] = "Cummins ISX";
                $this->servicesOfferts[] = "Cummins ISB";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Fleet Charge";
                $this->servicesOfferts[] = "Nettoyage de réservoir de carburant";
                $this->servicesOfferts[] = "Équipement Huck Bolt";
                $this->servicesOfferts[] = "Idealease";
                $this->servicesOfferts[] = "OnCommand Prev Maint";
                $this->servicesOfferts[] = "Service partenaire";
                $this->servicesOfferts[] = "Remorquage";
                $this->servicesOfferts[] = "Stationnement pour remorque";
                $this->servicesOfferts[] = "Réparation de remorque";
                $this->servicesOfferts[] = "ViS Check";
                $this->serviceRoutierTitre = "";
                $this->serviceRoutierTelephone[] = "";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "Camions%20International%20%C3%89lite";
                $this->parametreDemandePiecesNomSuccursale = "Camions%20International%20%C3%89lite";
                break;
            case nomSuccursale::Shawinigan:
                $this->isSuccursale = 1;
                $this->isPointService = 0;
                $this->nomLong = "Garage Robert";
                $this->adresse = "9850, boul des Hêtres ";
                $this->ville = "Shawinigan";
                $this->province = "Québec";
                $this->codePostal = "G9N 4Y3";
                $this->telephones[] = "Téléphone : 819 539-6417";
                $this->telephones[] = "Sans frais : 800 663-0107";
                $this->telephones[] = "Télécopieur : 819 539-3536";
                $this->heureOuvertureLundi = "8:00 - 17:00";
                $this->heureOuvertureMardi = "8:00 - 17:00";
                $this->heureOuvertureMercredi = "8:00 - 17:00";
                $this->heureOuvertureJeudi = "8:00 - 17:00";
                $this->heureOuvertureVendredi = "8:00 - 17:00";
                $this->heureOuvertureSamedi = "Fermé";
                $this->heureOuvertureDimanche = "Fermé";
                $this->contacts = new Contact();
                $this->contacts->addItem(array("Serge Thibodeau", "Président"));
                $this->contacts->addItem(array("Pierre Poudrette", "Vice-président"));
                $this->contacts->addItem(array("Marc Lebrun", "Directeur du service","grobert-service@cgocable.ca"));
                $this->contacts->addItem(array("Claude Davidson", "Directeur des pièces","grobert-pièces@cgocable.ca"));
                $this->contacts->addItem(array("Marc André Gamelin", "Représentant des ventes","magamelin@camionbeaudoin.com"));
                $this->imageBatisse = "../../_assets/images/batisse/batisse-garage-robert.png";
                $this->imageBatisseALT= "Garage Robert";
                $this->servicesOfferts[] = "Service routier 24/7";
                $this->servicesOfferts[] = "Service accéléré";
                $this->servicesOfferts[] = "Cummins";
                $this->servicesOfferts[] = "CAT";
                $this->servicesOfferts[] = "Nettoyage DPF";
                $this->servicesOfferts[] = "Service routier"; 
                $this->servicesOfferts[] = "Service de carrosserie complet";
                $this->servicesOfferts[] = "Réparation boite de camion";
                $this->serviceRoutierTitre = "Service Routier";
                $this->serviceRoutierTelephone[] = "";
                $this->remorquageTitre = "";
                $this->remorquageInfo[] = "";
                $this->remorquageTelephones[] = "";
                $this->parametreBonTravailNomSuccursale = "Garage Robert";
                $this->parametreDemandePiecesNomSuccursale = "Garage Robert";
                $this->GoogleMapSRC = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2741.5253671513356!2d-72.71138334836269!3d46.596619579028236!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc64df0b295b3d9%3A0xf26322fa98abd028!2sGarage+Robert+Inc!5e0!3m2!1sfr!2sca!4v1487884811377";
                break;
//            case nomSuccursale::Joliette:
//                $this->isSuccursale = 1;
//                $this->isPointService = 0;
//                $this->nomLong = "";
//                $this->adresse = "";
//                $this->ville = "";
//                $this->province = "Québec";
//                $this->codePostal = "";
//                $this->telephones[] = "";
//                $this->telephones[] = "";
//                $this->telephones[] = "";
//                $this->heureOuvertureLundi = "";
//                $this->heureOuvertureMardi = "";
//                $this->heureOuvertureMercredi = "";
//                $this->heureOuvertureJeudi = "";
//                $this->heureOuvertureVendredi = "";
//                $this->heureOuvertureSamedi = "";
//                $this->heureOuvertureDimanche = "";
//                $this->contacts = new Contact();
//                $this->contacts->addItem(array("", "",""));
//                $this->imageBatisse = "../../_assets/images/batisse/.jpg";
//                $this->imageBatisseALT= "";
//                $this->servicesOfferts[] = "";
//                $this->serviceRoutierTitre = "Service Routier";
//                $this->serviceRoutierTelephone[] = "";
//                $this->remorquageTitre = "";
//                $this->remorquageInfo[] = "";
//                $this->remorquageTelephones[] = "";
//                $this->parametreBonTravailNomSuccursale = "";
//                $this->parametreDemandePiecesNomSuccursale = "";
                break;
            
            default:;
        }
    
        return true;
    }
}
?>